1.4
js-tasks-ru/jsbasic-20240219_burbuzin1 pull request #3
Opened 2024-02-23 21:08 UTC by burbuzin1

2024-02-23 21:09 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-02-23 21:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-02-24 06:40 UTC, koalex requested changes
Нужно решить **1-5**

2024-02-26 09:16 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-02-26 09:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-02-26 13:24 UTC, koalex requested changes
Теперь нужно решить **2-1**. Не добавляйте новые задачи пока не решите текущие

2024-02-26 15:16 UTC, burbuzin1 commented
> Теперь нужно решить **2-1**. Не добавляйте новые задачи пока не решите текущие

так  я решаю задачу, коммичу ее, добавляю следующую и происходит то, что происходит

2024-02-27 03:14 UTC, koalex commented
> > Теперь нужно решить **2-1**. Не добавляйте новые задачи пока не решите текущие
> 
> так я решаю задачу, коммичу ее, добавляю следующую и происходит то, что происходит. Посмотрите по тестам 1-5 решена, тест падает на 2.1. И так было всё время до этого

По задачнику вижу, что у вам добавлена **2-1**, но не решена. Давайте когда решите **2-1** я приму ПР и тогда продолжите след задачи

2024-03-02 09:28 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-02 15:37 UTC, koalex approved these changes

2024-03-02 15:38 UTC, merged